### ISSUE TITLE
Authentication crashes when user does not have a StackOverflow account

### ISSUE THREAD

**Issue by LucasLazaro** [geNAZt/passport-stackexchange#2]
Since it's named `stackexchange` strategy is good to mention that if the user does not have a StackOverflow account the library will throw an `TypeError`.

Backtrace:

```
/app/node_modules/passport-stackexchange/lib/passport-stackexchange/strategy.js:51
         json.items[0].provider = "stackexchange";
                                ^

 TypeError: Cannot set property 'provider' of undefined
     at clearStream.end (/app/node_modules/passport-stackexchange/lib/passport-stackexchange/strategy.js:51:32)
     at Gunzip.onend (_stream_readable.js:498:10)
     at Gunzip.g (events.js:273:16)
     at emitNone (events.js:85:20)
     at Gunzip.emit (events.js:179:7)
     at endReadableNT (_stream_readable.js:913:12)
     at _combinedTickCallback (internal/process/next_tick.js:74:11)
     at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by geNAZt** [comment]
https://www.npmjs.com/package/passport-stackexchange
